---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{CF_REPO_NAME}}
  labels:
    app: {{CF_REPO_NAME}}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      name: {{CF_REPO_NAME}}
      labels:
        app: {{CF_REPO_NAME}}
        tier: web
    spec:
      imagePullSecrets:
        - name: image-pull-secret
      containers:
        - name: {{CF_REPO_NAME}}
          image: {{BUILD_IMAGE}}
          imagePullPolicy: Always
          ports:
          - name: web
            containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
